swagger: "2.0"
info:
  description: "Find Correlation between currencies"
  version: "0.0.0"
  title: "Correlation of Currencies"
basePath: "/v0"
tags:
- name: "data"
  description: "Get data for analysis"
schemes:
- "http"
paths:
  /monitor:
    x-swagger-router-controller: "monitor"
    get:
      tags:
        - "monitor"
      operationId: "get"
      summary: "For monitoring"
      responses:
        200:
          description: "all is well"
        default:
          description: "unexpected error"
  /data:
    x-swagger-router-controller: "data"
    get:
      tags:
      - "data"
      summary: "Get data for analysis"
      description: ""
      operationId: "getData"
      produces:
      - "application/json"
      parameters:
      - name: "forYear"
        in: "query"
        description: "A year in a format YYYY"
        required: true
        type: "integer"
        format: "int32"
      - name: "forMonth"
        in: "query"
        description: "A month in a format MM"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Data"
        400:
          description: "Invalid request variables supplied"
definitions:
  Data:
    type: "object"
    required:
    - "btc_usd"
    - "eth_usd"
    - "from"
    - "to"
    properties:
      btc_usd:
        type: "string"
        example: "6 Months"
      eth_usd:
        type: "number"
        example: "0.6305"
      from:
        type: "string"
        example: "2017-10-01"
      to:
        type: "string"
        example: "2018-04-30"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"